# Generated by Django 4.2.7 on 2026-04-25 11:44

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("pgmaster_auth", "0001_initial"),
        ("pg", "0001_initial"),
        ("rooms", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Tenant",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(default=True)),
                ("tenant_name", models.CharField(max_length=255)),
                ("father_name", models.CharField(blank=True, max_length=255)),
                ("mother_name", models.CharField(blank=True, max_length=255)),
                (
                    "phone",
                    models.CharField(
                        max_length=15,
                        validators=[
                            django.core.validators.RegexValidator(
                                message="Phone number must be valid.",
                                regex="^\\+?1?\\d{9,15}$",
                            )
                        ],
                    ),
                ),
                ("alternate_phone", models.CharField(blank=True, max_length=15)),
                ("email", models.EmailField(blank=True, max_length=254)),
                (
                    "aadhar_number",
                    models.CharField(
                        max_length=12,
                        unique=True,
                        validators=[
                            django.core.validators.RegexValidator(
                                message="Aadhar number must be 12 digits.",
                                regex="^\\d{12}$",
                            )
                        ],
                    ),
                ),
                (
                    "id_proof_type",
                    models.CharField(
                        choices=[
                            ("aadhar", "Aadhar"),
                            ("pan", "PAN"),
                            ("driving_license", "Driving License"),
                            ("passport", "Passport"),
                        ],
                        default="aadhar",
                        max_length=20,
                    ),
                ),
                (
                    "id_proof",
                    models.FileField(blank=True, null=True, upload_to="id_proofs/"),
                ),
                (
                    "photo",
                    models.ImageField(
                        blank=True, null=True, upload_to="tenant_photos/"
                    ),
                ),
                ("permanent_address", models.TextField()),
                ("city", models.CharField(max_length=100)),
                ("state", models.CharField(max_length=100)),
                ("pincode", models.CharField(max_length=6)),
                (
                    "institution_type",
                    models.CharField(
                        choices=[
                            ("college", "College"),
                            ("company", "Company"),
                            ("other", "Other"),
                        ],
                        default="college",
                        max_length=20,
                    ),
                ),
                ("institution_name", models.CharField(blank=True, max_length=255)),
                ("course_name", models.CharField(blank=True, max_length=255)),
                (
                    "emergency_contact_name",
                    models.CharField(blank=True, max_length=255),
                ),
                (
                    "emergency_contact_phone",
                    models.CharField(blank=True, max_length=15),
                ),
                ("join_date", models.DateField()),
                ("notice_date", models.DateField(blank=True, null=True)),
                ("vacate_date", models.DateField(blank=True, null=True)),
                ("monthly_rent", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "security_deposit",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "Active"),
                            ("notice_period", "Notice Period"),
                            ("vacated", "Vacated"),
                            ("inactive", "Inactive"),
                        ],
                        default="active",
                        max_length=20,
                    ),
                ),
                (
                    "advance_paid",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                ("notes", models.TextField(blank=True)),
                (
                    "bed",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="tenants",
                        to="rooms.bed",
                    ),
                ),
                (
                    "pg",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tenants",
                        to="pg.pgprofile",
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        blank=True,
                        limit_choices_to={"role": "tenant"},
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tenant_profile",
                        to="pgmaster_auth.user",
                    ),
                ),
            ],
            options={
                "ordering": ["-join_date"],
                "unique_together": {("pg", "aadhar_number")},
            },
        ),
    ]
