# Generated by Django 4.2.7 on 2026-04-25 11:44

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Notice",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(default=True)),
                ("title", models.CharField(max_length=255)),
                (
                    "notice_type",
                    models.CharField(
                        choices=[
                            ("rent_reminder", "Rent Reminder"),
                            ("maintenance", "Maintenance/Shutdown"),
                            ("rules_update", "Rules Update"),
                            ("event", "Event Notice"),
                            ("other", "Other"),
                        ],
                        max_length=20,
                    ),
                ),
                ("content", models.TextField()),
                ("send_to_all", models.BooleanField(default=True)),
                ("target_rooms", models.JSONField(blank=True, default=list)),
                ("is_sent", models.BooleanField(default=False)),
                ("sent_date", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
    ]
