# Generated by Django 4.2.7 on 2026-04-25 11:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("pg", "0001_initial"),
        ("notices", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="notice",
            name="pg",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="notices",
                to="pg.pgprofile",
            ),
        ),
    ]
