# Generated by Django 4.2.7 on 2026-04-25 11:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("pg", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Room",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(default=True)),
                ("room_number", models.CharField(max_length=20)),
                ("floor", models.IntegerField()),
                (
                    "sharing_type",
                    models.IntegerField(
                        choices=[
                            (1, "Single"),
                            (2, "Double/2-Sharing"),
                            (3, "3-Sharing"),
                            (4, "4-Sharing"),
                        ]
                    ),
                ),
                (
                    "room_type",
                    models.CharField(
                        choices=[("ac", "AC"), ("non_ac", "Non-AC")], max_length=10
                    ),
                ),
                ("monthly_rent", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "advance_required",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                ("description", models.TextField(blank=True, null=True)),
                ("amenities", models.JSONField(blank=True, default=list)),
                (
                    "pg",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="rooms",
                        to="pg.pgprofile",
                    ),
                ),
            ],
            options={
                "ordering": ["floor", "room_number"],
                "unique_together": {("pg", "room_number")},
            },
        ),
        migrations.CreateModel(
            name="Bed",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(default=True)),
                ("bed_number", models.CharField(max_length=1)),
                ("monthly_rent", models.DecimalField(decimal_places=2, max_digits=10)),
                ("occupied", models.BooleanField(default=False)),
                (
                    "room",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="beds",
                        to="rooms.room",
                    ),
                ),
            ],
            options={
                "ordering": ["bed_number"],
                "unique_together": {("room", "bed_number")},
            },
        ),
    ]
