# Generated by Django 4.2.7 on 2026-04-25 11:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("payments", "0001_initial"),
        ("tenants", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="securitydeposit",
            name="tenant",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="security_deposit_record",
                to="tenants.tenant",
            ),
        ),
        migrations.AddField(
            model_name="paymentreceipt",
            name="payment",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="receipt",
                to="payments.payment",
            ),
        ),
        migrations.AddField(
            model_name="payment",
            name="tenant",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="payments",
                to="tenants.tenant",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="payment",
            unique_together={("tenant", "month")},
        ),
    ]
