# Generated by Django 4.2.7 on 2026-04-25 11:44

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="PGProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(default=True)),
                ("name", models.CharField(max_length=255)),
                ("owner_name", models.CharField(max_length=255)),
                ("address", models.TextField()),
                ("city", models.CharField(max_length=100)),
                ("state", models.CharField(max_length=100)),
                ("pincode", models.CharField(max_length=6)),
                (
                    "phone",
                    models.CharField(
                        max_length=15,
                        validators=[
                            django.core.validators.RegexValidator(
                                message="Phone number must be valid.",
                                regex="^\\+?1?\\d{9,15}$",
                            )
                        ],
                    ),
                ),
                ("email", models.EmailField(max_length=254)),
                ("gst_number", models.CharField(blank=True, max_length=15, null=True)),
                (
                    "bank_account",
                    models.CharField(blank=True, max_length=20, null=True),
                ),
                ("ifsc_code", models.CharField(blank=True, max_length=11, null=True)),
                (
                    "logo",
                    models.ImageField(blank=True, null=True, upload_to="pg_logos/"),
                ),
                (
                    "subscription_plan",
                    models.CharField(
                        choices=[
                            ("starter", "Starter"),
                            ("growth", "Growth"),
                            ("premium", "Premium"),
                        ],
                        default="starter",
                        max_length=20,
                    ),
                ),
                ("subscription_end_date", models.DateField(blank=True, null=True)),
                ("total_rooms", models.IntegerField(default=0)),
                ("total_beds", models.IntegerField(default=0)),
            ],
            options={
                "verbose_name_plural": "PG Profiles",
            },
        ),
        migrations.CreateModel(
            name="PGSettings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(default=True)),
                ("auto_generate_rent", models.BooleanField(default=True)),
                ("rent_due_day", models.IntegerField(default=1)),
                (
                    "late_fee_percentage",
                    models.DecimalField(decimal_places=2, default=5.0, max_digits=5),
                ),
                ("enable_electricity_charges", models.BooleanField(default=False)),
                (
                    "electricity_rate",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                ("enable_water_charges", models.BooleanField(default=False)),
                (
                    "water_rate",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                ("send_email_reminders", models.BooleanField(default=True)),
                ("send_sms_reminders", models.BooleanField(default=False)),
                (
                    "default_complaint_priority",
                    models.CharField(
                        choices=[
                            ("low", "Low"),
                            ("medium", "Medium"),
                            ("high", "High"),
                        ],
                        default="medium",
                        max_length=20,
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "PG Settings",
            },
        ),
        migrations.CreateModel(
            name="PGStaff",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "designation",
                    models.CharField(
                        choices=[
                            ("manager", "Manager"),
                            ("caretaker", "Caretaker"),
                            ("cleaner", "Cleaner"),
                            ("other", "Other"),
                        ],
                        max_length=50,
                    ),
                ),
                ("joining_date", models.DateField()),
                (
                    "salary",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                (
                    "pg",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="staff_members",
                        to="pg.pgprofile",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "PG Staff",
            },
        ),
    ]
