# Generated by Django 4.2.7 on 2026-04-25 11:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("pgmaster_auth", "0001_initial"),
        ("pg", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="pgstaff",
            name="user",
            field=models.OneToOneField(
                limit_choices_to={"role": "staff"},
                on_delete=django.db.models.deletion.CASCADE,
                related_name="pg_staff",
                to="pgmaster_auth.user",
            ),
        ),
        migrations.AddField(
            model_name="pgsettings",
            name="pg",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="settings",
                to="pg.pgprofile",
            ),
        ),
        migrations.AddField(
            model_name="pgprofile",
            name="owner",
            field=models.OneToOneField(
                limit_choices_to={"role": "pg_owner"},
                on_delete=django.db.models.deletion.CASCADE,
                related_name="pg_profile",
                to="pgmaster_auth.user",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="pgstaff",
            unique_together={("pg", "user")},
        ),
    ]
